language: python
os: linux
dist: bionic
cache: pip
services:
  - docker
before_install:
  - docker-compose up -d
  - docker exec -ti postgres psql -U postgres -c "CREATE DATABASE metrics;"
install:
  - make travis-setup
python:
  - "3.8"
script:
  - make ci
